# Site
name: 'Nandan Dev'
description: 'A Polyglot Developer Who Is Passionate About Technology.'
logo: 'assets/images/logo.png'
favicon: '/assets/images/favicon.ico'
baseurl: ''
disqus: 'nandan_dev'
email: 'its.nandanbn@gmail.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    nandan:
      name:           Nandan BN
      site:           https://nandan.dev
      avatar:         /assets/images/nandan_avatar.png
      bio:            "Hi, I am Nandan"
      email:          its.nandanbn@gmail.com
      twitter:        https://twitter.com/ItsNandanDev
 
# Defaults
defaults:
  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: nandan
      avatar: /assets/images/nandan.png
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10
paginate_path: "blog/page:num/"

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]